# Generated by Django 2.2.1 on 2019-06-03 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='种类名称')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='ProductClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='产品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='产品价格')),
                ('count', models.IntegerField(default=0, verbose_name='产品库存')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.CategoryClass', verbose_name='产品种类')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
